name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag corpsite:1.0
    - name: docker tag
      run: docker tag corpsite:1.0  docker.pkg.github.com/technobeads/corporatesite/corpsite:latest
    - name: docker login
      env:
        DOCKER_LOGIN: ${{secrets.DOCKER_LOGIN}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD https://docker.pkg.github.com
    - name: docker push
      run: docker push docker.pkg.github.com/technobeads/corporatesite/corpsite:latest
